import './globals.css';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { ThemeProviders } from '@/context/ThemeContext';
import { auth } from '@/auth';
import { cn } from '@/lib/utils';

const poppins = Poppins({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang='en' className=''>
      <body className={cn('transition-colors duration-50', poppins.className)}>
        <SessionProvider session={session}>
          <ThemeProviders>
            <div className='min-h-full w-full bg-[radial-gradient(ellipse_at_bottom,_var(--tw-gradient-stops))] from-green-400 via-fuchsia-200 to-sky-700'>
              {children}
            </div>
          </ThemeProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
